//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFulAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public string SchoolID { get; set; }
        public string School_Name { get; set; }
        public string City { get; set; }
        public string Directorate { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public int RawID { get; set; }
    }
}
